/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package si_piket_smkn3;

import java.awt.Graphics2D;
import java.awt.RenderingHints;
import java.awt.image.BufferedImage;
import java.io.File;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;



/**
 *
 * @author tawakida
 */
public class frm_utama extends javax.swing.JFrame {

    /**
     * Creates new form frm_utama
     */
    
    frm_ubah_guru ubah_guru = new frm_ubah_guru();
    public static String status_login;
    
    public frm_utama() {
        initComponents();
        tampilGbrJabar();
        tampilGbrSmkn3();               
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    //Method untuk memanggil gambar
    public static BufferedImage loadImage(String ref){
        BufferedImage bimg = null;
        try {
            bimg = ImageIO.read(new File(ref));
        } catch (Exception e) {
            e.printStackTrace();
        }
        return bimg;
    }
    
    //method untuk resize image
    public static BufferedImage resize(BufferedImage img,int newW, int newH){
        int w = img.getWidth();
        int h = img.getHeight();
        BufferedImage dimg = dimg = new BufferedImage(newW, newH,img.getType());
        Graphics2D g = dimg.createGraphics();
        g.setRenderingHint(RenderingHints.KEY_INTERPOLATION, RenderingHints.VALUE_INTERPOLATION_BILINEAR);
        g.drawImage(img, 0, 0,newW,newH,0,0,w,h,null);
        g.dispose();
        return  dimg;
    }
    
    //method untuk menampilkan gambar jabar pada jlabel
    public void tampilGbrJabar(){
        String urlGambar = "src/img/jabar.png";
        BufferedImage loadImg = loadImage(urlGambar);
        ImageIcon imageIcon = new ImageIcon(resize(loadImg,gbr_jabar.getWidth(),gbr_jabar.getHeight()));
        gbr_jabar.setIcon(imageIcon);
    }
    
    public void tampilGbrSmkn3(){
        String urlGambar = "src/img/logo_smkn3.png";
        BufferedImage loadImg = loadImage(urlGambar);
        ImageIcon imageIcon = new ImageIcon(resize(loadImg,gbr_smkn3.getWidth(),gbr_smkn3.getHeight()));
        gbr_smkn3.setIcon(imageIcon);
    }
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu4 = new javax.swing.JMenu();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuBar3 = new javax.swing.JMenuBar();
        jMenu6 = new javax.swing.JMenu();
        jMenu7 = new javax.swing.JMenu();
        gbr_jabar = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        gbr_smkn3 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_siswa = new javax.swing.JMenu();
        jMenuItem_tampil_siswa = new javax.swing.JMenuItem();
        jMenuItem_tambah_siswa = new javax.swing.JMenuItem();
        jMenuItem_ubah_siswa = new javax.swing.JMenuItem();
        jMenuItem_hapus_siswa = new javax.swing.JMenuItem();
        menu_guru = new javax.swing.JMenu();
        jMenuItem_tampil_guru = new javax.swing.JMenuItem();
        jMenuItem_tambah_guru = new javax.swing.JMenuItem();
        jMenuItem_ubah_guru = new javax.swing.JMenuItem();
        jMenuItem_hapus_guru = new javax.swing.JMenuItem();
        menu_piket = new javax.swing.JMenu();
        jMenuItem_tambah_piket = new javax.swing.JMenuItem();
        jMenuItem_ubah_piket = new javax.swing.JMenuItem();
        jMenuItem_hapus_piket = new javax.swing.JMenuItem();
        jMenuItem_tampil = new javax.swing.JMenuItem();
        jMenuItem_tampil_tanggal = new javax.swing.JMenuItem();
        menu_logout = new javax.swing.JMenu();

        jMenuItem4.setText("jMenuItem4");

        jMenu4.setText("File");
        jMenuBar2.add(jMenu4);

        jMenu5.setText("Edit");
        jMenuBar2.add(jMenu5);

        jMenuItem1.setText("jMenuItem1");

        jMenu6.setText("File");
        jMenuBar3.add(jMenu6);

        jMenu7.setText("Edit");
        jMenuBar3.add(jMenu7);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistem Informasi Piket SMKN 3 Bandung");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        gbr_jabar.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sistem Informasi Piket SMK Negeri 3 Bandung");

        gbr_smkn3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        menu_siswa.setText("Siswa");

        jMenuItem_tampil_siswa.setText("Tampil Data Siswa");
        jMenuItem_tampil_siswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_tampil_siswaActionPerformed(evt);
            }
        });
        menu_siswa.add(jMenuItem_tampil_siswa);

        jMenuItem_tambah_siswa.setText("Tambah Data Siswa");
        jMenuItem_tambah_siswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_tambah_siswaActionPerformed(evt);
            }
        });
        menu_siswa.add(jMenuItem_tambah_siswa);

        jMenuItem_ubah_siswa.setText("Ubah Data Siswa");
        jMenuItem_ubah_siswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ubah_siswaActionPerformed(evt);
            }
        });
        menu_siswa.add(jMenuItem_ubah_siswa);

        jMenuItem_hapus_siswa.setText("Hapus Data Siswa");
        jMenuItem_hapus_siswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_hapus_siswaActionPerformed(evt);
            }
        });
        menu_siswa.add(jMenuItem_hapus_siswa);

        jMenuBar1.add(menu_siswa);

        menu_guru.setText("Guru");

        jMenuItem_tampil_guru.setText("Tampil Data Guru");
        jMenuItem_tampil_guru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_tampil_guruActionPerformed(evt);
            }
        });
        menu_guru.add(jMenuItem_tampil_guru);

        jMenuItem_tambah_guru.setText("Tambah Data Guru");
        jMenuItem_tambah_guru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_tambah_guruActionPerformed(evt);
            }
        });
        menu_guru.add(jMenuItem_tambah_guru);

        jMenuItem_ubah_guru.setText("Ubah Data Guru");
        jMenuItem_ubah_guru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ubah_guruActionPerformed(evt);
            }
        });
        menu_guru.add(jMenuItem_ubah_guru);

        jMenuItem_hapus_guru.setText("Hapus Data Guru");
        jMenuItem_hapus_guru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_hapus_guruActionPerformed(evt);
            }
        });
        menu_guru.add(jMenuItem_hapus_guru);

        jMenuBar1.add(menu_guru);

        menu_piket.setText("Piket");

        jMenuItem_tambah_piket.setText("Tambah Data Piket");
        jMenuItem_tambah_piket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_tambah_piketActionPerformed(evt);
            }
        });
        menu_piket.add(jMenuItem_tambah_piket);

        jMenuItem_ubah_piket.setText("Ubah Data Piket");
        jMenuItem_ubah_piket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_ubah_piketActionPerformed(evt);
            }
        });
        menu_piket.add(jMenuItem_ubah_piket);

        jMenuItem_hapus_piket.setText("Hapus Data Piket");
        jMenuItem_hapus_piket.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_hapus_piketActionPerformed(evt);
            }
        });
        menu_piket.add(jMenuItem_hapus_piket);

        jMenuItem_tampil.setText("Tampil Data Piket");
        jMenuItem_tampil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_tampilActionPerformed(evt);
            }
        });
        menu_piket.add(jMenuItem_tampil);

        jMenuItem_tampil_tanggal.setText("Tampil Data Piket Berdasarkan Tanggal");
        jMenuItem_tampil_tanggal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem_tampil_tanggalActionPerformed(evt);
            }
        });
        menu_piket.add(jMenuItem_tampil_tanggal);

        jMenuBar1.add(menu_piket);

        menu_logout.setText("Logout");
        menu_logout.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                menu_logoutMouseClicked(evt);
            }
        });
        jMenuBar1.add(menu_logout);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(115, 115, 115)
                .addComponent(gbr_jabar, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(gbr_smkn3, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(135, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 467, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gbr_jabar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gbr_smkn3, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(79, 79, 79))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(27, 27, 27)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(221, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem_tampil_siswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_tampil_siswaActionPerformed
        // TODO add your handling code here:
        //menampilkan frame siswa
        frm_tampil_siswa siswa = new frm_tampil_siswa();
        siswa.setVisible(true);
        
        //menutup frame utama
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem_tampil_siswaActionPerformed

    private void jMenuItem_tambah_siswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_tambah_siswaActionPerformed
        // TODO add your handling code here:
        frm_tambah_siswa siswa = new frm_tambah_siswa();
        siswa.setVisible(true);
        
        //menutup frame utama
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem_tambah_siswaActionPerformed

    private void jMenuItem_ubah_siswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ubah_siswaActionPerformed
        // TODO add your handling code here:
        frm_ubah_siswa ubah_siswa = new frm_ubah_siswa();
        ubah_siswa.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem_ubah_siswaActionPerformed

    private void jMenuItem_hapus_siswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_hapus_siswaActionPerformed
        // TODO add your handling code here:
        frm_hapus_siswa hapus_siswa = new frm_hapus_siswa();
        hapus_siswa.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem_hapus_siswaActionPerformed

    private void jMenuItem_tampil_guruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_tampil_guruActionPerformed
        // TODO add your handling code here:
        frm_tampil_guru tampil_guru = new frm_tampil_guru();
        tampil_guru.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem_tampil_guruActionPerformed

    private void jMenuItem_tambah_guruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_tambah_guruActionPerformed
        // TODO add your handling code here:
        frm_tambah_guru tambah_guru = new frm_tambah_guru();
        tambah_guru.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem_tambah_guruActionPerformed

    private void jMenuItem_ubah_guruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ubah_guruActionPerformed
        // TODO add your handling code here:
        
        ubah_guru.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem_ubah_guruActionPerformed

    private void jMenuItem_hapus_guruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_hapus_guruActionPerformed
        // TODO add your handling code here:
        frm_hapus_guru hapus_guru = new frm_hapus_guru();
        hapus_guru.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem_hapus_guruActionPerformed

    private void jMenuItem_tambah_piketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_tambah_piketActionPerformed
        // TODO add your handling code here:
        frm_tambah_piket.status_login = status_login;
        frm_tambah_piket tambah_piket = new frm_tambah_piket();
        tambah_piket.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem_tambah_piketActionPerformed

    private void jMenuItem_ubah_piketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_ubah_piketActionPerformed
        // TODO add your handling code here:
        frm_ubah_piket.status_login = status_login;
        frm_ubah_piket ubah_piket = new frm_ubah_piket();
        ubah_piket.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem_ubah_piketActionPerformed

    private void jMenuItem_hapus_piketActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_hapus_piketActionPerformed
        // TODO add your handling code here:
        frm_hapus_piket.status_login = status_login;
        frm_hapus_piket hapus_piket = new frm_hapus_piket();
        hapus_piket.setVisible(true);
        
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem_hapus_piketActionPerformed

    private void jMenuItem_tampilActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_tampilActionPerformed
        // TODO add your handling code here:
        frm_tampil_piket.status_login = status_login;
        frm_tampil_piket tampil_piketnya = new frm_tampil_piket();
        tampil_piketnya.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem_tampilActionPerformed

    private void jMenuItem_tampil_tanggalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem_tampil_tanggalActionPerformed
        // TODO add your handling code here:
        frm_tampil_piket_tanggal.status_login = status_login;
        frm_tampil_piket_tanggal tampil_piket_tanggal = new frm_tampil_piket_tanggal();
        tampil_piket_tanggal.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jMenuItem_tampil_tanggalActionPerformed

    private void menu_logoutMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_menu_logoutMouseClicked
        // TODO add your handling code here:
        int selectedOption = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin Logout ?","Konfirmasi Logout",JOptionPane.YES_NO_OPTION);
        if (selectedOption == JOptionPane.YES_OPTION) {            
                status_login = null;
                frm_login login = new frm_login();
                login.setVisible(true);
                this.setVisible(false);                
            }
        else {
            setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);                       
        }
    }//GEN-LAST:event_menu_logoutMouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        int selectedOption = JOptionPane.showConfirmDialog(null, "Apakah anda yakin ingin Logout dan Keluar ?","Konfirmasi Logout dan Keluar",JOptionPane.YES_NO_OPTION);
        if (selectedOption == JOptionPane.YES_OPTION) {            
                System.exit(0);
            }
        else {
            setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);                       
        }
    }//GEN-LAST:event_formWindowClosing

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frm_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frm_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frm_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frm_utama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frm_utama().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel gbr_jabar;
    private javax.swing.JLabel gbr_smkn3;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuBar jMenuBar3;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem_hapus_guru;
    private javax.swing.JMenuItem jMenuItem_hapus_piket;
    private javax.swing.JMenuItem jMenuItem_hapus_siswa;
    private javax.swing.JMenuItem jMenuItem_tambah_guru;
    private javax.swing.JMenuItem jMenuItem_tambah_piket;
    private javax.swing.JMenuItem jMenuItem_tambah_siswa;
    private javax.swing.JMenuItem jMenuItem_tampil;
    private javax.swing.JMenuItem jMenuItem_tampil_guru;
    private javax.swing.JMenuItem jMenuItem_tampil_siswa;
    private javax.swing.JMenuItem jMenuItem_tampil_tanggal;
    private javax.swing.JMenuItem jMenuItem_ubah_guru;
    private javax.swing.JMenuItem jMenuItem_ubah_piket;
    private javax.swing.JMenuItem jMenuItem_ubah_siswa;
    public static javax.swing.JMenu menu_guru;
    private javax.swing.JMenu menu_logout;
    private javax.swing.JMenu menu_piket;
    public static javax.swing.JMenu menu_siswa;
    // End of variables declaration//GEN-END:variables
}
